__author__ = "Andrei Guliaev"
__copyright__ = "Copyright 2026, Andrei Guliaev"
__email__ = "andrei.guliaev@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"


rule all:
    input:
        compile_output_file_list,


module cnv_sv:
    snakefile:
        github(
            "hydra-genetics/cnv_sv",
            path="workflow/Snakefile",
            tag=config.get("module_versions", {}).get("cnv_sv", "v2.0.0"),
        )
    config:
        config


# Run Sniffles2 on the mapped BAM referenced in units.tsv.
# Override bam/bai/ref; tandem-repeats comes from config["sniffles2_call"]["tandem_repeats"]
# via the module's get_tr_bed (params.tandem_repeats), so no params override is needed.
use rule sniffles2_call from cnv_sv as cnv_sv_sniffles2 with:
    input:
        bam=lambda wildcards: get_bam(wildcards)[0],
        bai=lambda wildcards: get_bam(wildcards)[1],
        ref=config.get("reference", {}).get("fasta", ""),


# bgzip + tabix the Sniffles2 VCF
use rule bgzip from cnv_sv as cnv_sv_bgzip_sniffles with:
    wildcard_constraints:
        file="^cnv_sv/sniffles2_call/.+",


use rule tabix from cnv_sv as cnv_sv_tabix_sniffles with:
    wildcard_constraints:
        file="^cnv_sv/sniffles2_call/.+",


rule compile_xlsx_report:
    input:
        vcf_sv="cnv_sv/sniffles2_call/{sample}_{type}.vcf.gz",
        tbi="cnv_sv/sniffles2_call/{sample}_{type}.vcf.gz.tbi",
    output:
        xlsx=temp("reports/xlsx_reports/{sample}_{type}.sniffles2.xlsx"),
    params:
        software_versions={
            "sniffles2": config.get("sniffles2_call", {}).get("container", ""),
        },
    log:
        "reports/xlsx_reports/{sample}_{type}.sniffles2.xlsx.log",
    benchmark:
        repeat(
            "reports/xlsx_reports/{sample}_{type}.sniffles2.xlsx.benchmark.tsv",
            config.get("compile_xlsx_report", {}).get("benchmark_repeats", 1),
        )
    threads: config.get("compile_xlsx_report", {}).get("threads", config["default_resources"]["threads"])
    resources:
        mem_mb=config.get("compile_xlsx_report", {}).get("mem_mb", config["default_resources"]["mem_mb"]),
        mem_per_cpu=config.get("compile_xlsx_report", {}).get("mem_per_cpu", config["default_resources"]["mem_per_cpu"]),
        partition=config.get("compile_xlsx_report", {}).get("partition", config["default_resources"]["partition"]),
        threads=config.get("compile_xlsx_report", {}).get("threads", config["default_resources"]["threads"]),
        time=config.get("compile_xlsx_report", {}).get("time", config["default_resources"]["time"]),
    container:
        config.get("compile_xlsx_report", {}).get("container", config["default_container"])
    message:
        "{rule}: compile Sniffles2 SVs into Excel report for {wildcards.sample}_{wildcards.type}"
    script:
        "scripts/compile_xlsx_report_sv.py"
