---
directory: "results"
files:
  - name: "sniffles2 vcf"
    input: "cnv_sv/sniffles2_call/{sample}_{type}.vcf.gz"
    output: "sv/{sample}_{type}.sniffles2.vcf.gz"
  - name: "sniffles2 xlsx report"
    input: "reports/xlsx_reports/{sample}_{type}.sniffles2.xlsx"
    output: "sv/{sample}_{type}.sniffles2.xlsx"
  - name: "sniffles2 joint vcf"
    input: "cnv_sv/sniffles2_joint/{sample}.vcf.gz"
    output: "sv/{sample}.sniffles2_joint.vcf.gz"
  - name: "sniffles2 joint vcf tbi"
    input: "cnv_sv/sniffles2_joint/{sample}.vcf.gz.tbi"
    output: "sv/{sample}.sniffles2_joint.vcf.gz.tbi"
  - name: "sniffles2 joint xlsx report"
    input: "reports/xlsx_reports/{sample}.sniffles2_joint.xlsx"
    output: "sv/{sample}.sniffles2_joint.xlsx"
